
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 11 15:16:16 CET 2026
//----------------------------------------------------



/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 11;
  public static final int PLUS = 14;
  public static final int RPAREN = 20;
  public static final int SEMI = 18;
  public static final int CHAR = 7;
  public static final int IN = 12;
  public static final int FILE = 9;
  public static final int END = 5;
  public static final int RETURN = 3;
  public static final int LPAREN = 19;
  public static final int COLON = 17;
  public static final int ID = 21;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 4;
  public static final int DO = 13;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int MINUS = 15;
  public static final int CONST = 22;
  public static final int error = 1;
  public static final int ASSIGN = 16;
  public static final int INTEGER = 6;
  public static final int OPEN = 10;
}

